
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Friendship
 * 
 */
export type Friendship = Prisma.FriendshipModel
/**
 * Model Token
 * 
 */
export type Token = Prisma.TokenModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Server
 * 
 */
export type Server = Prisma.ServerModel
/**
 * Model Member
 * 
 */
export type Member = Prisma.MemberModel
/**
 * Model Channel
 * 
 */
export type Channel = Prisma.ChannelModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model ConversationParticipant
 * 
 */
export type ConversationParticipant = Prisma.ConversationParticipantModel
/**
 * Model DirectMessage
 * 
 */
export type DirectMessage = Prisma.DirectMessageModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
