
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  MEMBER: 'MEMBER',
  MODERATOR: 'MODERATOR',
  ADMIN: 'ADMIN',
  OWNER: 'OWNER'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const AuthMethod = {
  CREDENTIALS: 'CREDENTIALS',
  GOOGLE: 'GOOGLE',
  YANDEX: 'YANDEX',
  OAUTH: 'OAUTH'
} as const

export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod]


export const ChannelType = {
  TEXT: 'TEXT',
  VOICE: 'VOICE'
} as const

export type ChannelType = (typeof ChannelType)[keyof typeof ChannelType]


export const MemberRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  MEMBER: 'MEMBER'
} as const

export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole]


export const TokenType = {
  VERIFICATION: 'VERIFICATION',
  OAUTH: 'OAUTH',
  TWOFACTOR: 'TWOFACTOR'
} as const

export type TokenType = (typeof TokenType)[keyof typeof TokenType]


export const ConversationType = {
  DIRECT: 'DIRECT',
  GROUP: 'GROUP'
} as const

export type ConversationType = (typeof ConversationType)[keyof typeof ConversationType]


export const FriendshipStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  BLOCKED: 'BLOCKED'
} as const

export type FriendshipStatus = (typeof FriendshipStatus)[keyof typeof FriendshipStatus]


export const RolePermissions = {
  CAN_EDIT_CHANNEL: 'CAN_EDIT_CHANNEL',
  CAN_EDIT_SERVER: 'CAN_EDIT_SERVER',
  CAN_EDIT_ROLE: 'CAN_EDIT_ROLE',
  CAN_GRANT_ROLE: 'CAN_GRANT_ROLE',
  CAN_CREATE_CHANNEL: 'CAN_CREATE_CHANNEL',
  CAN_CREATE_ROLE: 'CAN_CREATE_ROLE',
  CAN_INVITE: 'CAN_INVITE',
  CAN_BAN: 'CAN_BAN',
  CAN_KICK: 'CAN_KICK',
  CAN_MUTE: 'CAN_MUTE',
  CAN_DELETE_CHANNEL: 'CAN_DELETE_CHANNEL',
  CAN_DELETE_SERVER: 'CAN_DELETE_SERVER',
  CAN_DELETE_MESSAGE: 'CAN_DELETE_MESSAGE',
  CAN_DELETE_ROLE: 'CAN_DELETE_ROLE',
  OWNER: 'OWNER'
} as const

export type RolePermissions = (typeof RolePermissions)[keyof typeof RolePermissions]
